Repository Aeroponz/SOEN341, pull requests merged in 2020-01, with the labels that each got.

#1 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-update.md
  .github/ISSUE_TEMPLATE/new-feature.md
Labels: Doc, GitHub

#2 Repo Setup: Templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation-update.md
  .github/ISSUE_TEMPLATE/new-feature.md
  .github/pull_request_template.md
  README.md
Labels: GitHub

#4 Adding HTML homepage base
  HomepageBase.html
Labels: Doc

#26 Feature/Platform_Logo
  Ressources/Logo.psd
  Ressources/LogoCircle.png
  Ressources/LogoSquare.png
  Ressources/LogoUncropped.png
Labels: Dev

#27 Update read me
  README.md
Labels: Doc

#30 Layout wip
  HomepageBase.html
  HomepageStyle.css
  SettingsPage.html
  SettingsStyle.css
  UserPage.html
Labels: Dev

#31 [DEV] Database Setup with User Account Tables
  db/BluDBInfo.txt
  db/BluUserSetup.sql
  db/dbPHPexample.php
Labels: Dev

#32 [DEV] Posts + Comments DB setup
  db/BluDBInfo.txt
  db/BluPostSetup.sql
  db/images/meme_test_pic.png
Labels: Dev
