Repository Aeroponz/SOEN341, pull requests merged in 2020-03, with the labels that each got.

#118 Update viewposts and comments with funtions
  src/db/commentToDB.php
  src/db/followToDB.php
  src/pages/FunctionBlocks/followJS.js
  src/pages/ViewPostPage/viewPost.php
  src/pages/ViewPostPage/viewPostClass.php
  src/pages/css/viewPostStyle.css
Labels: Bug

#119 SignUp Tests
  .travis.yml
  src/db/DBConfig.php
  src/pages/FunctionBlocks/AddEmailToDB.php
  src/pages/FunctionBlocks/checkUsernameAndPassword.php
  src/pages/LoginPage/loginPage.php
  src/pages/SignUpPage/ModalPopUp.php
  src/pages/SignUpPage/SignUp.php
  src/pages/SignUpPage/signUp.php
  src/pages/SignUpPage/signUpPage.php
  src/tests/SignUpTest.php
  src/tests/TestFunction.php
  src/tests/UploadPostToDbTest.php
Labels: Bug, High-Level, Sub-Task, User Story

#121 Login Restructure And Tests
  .travis.yml
  src/pages/LoginPage/LogIn.php
  src/pages/LoginPage/loginPage.php
  src/tests/LoginTest.php
  src/tests/SignUpTest.php
  src/tests/UploadPostToDbTest.php
Labels: Bug, Sub-Task, User Story

#123 Login Patch (SQL query)
  src/pages/LoginPage/LogIn.php
Labels: Bug

#122 Bug/fix view post database
  src/db/commentToDB.php
  src/db/followToDB.php
  src/pages/ViewPostPage/viewPost.php
  src/pages/ViewPostPage/viewPostClass.php
Labels: Bug

#126 Update README.md
  README.md
Labels: Doc

#128 Fixed typos leading to uploading error
  src/db/UploadClass.php
  src/db/uploadPostToDB.php
Labels: Bug

#129 Adding Blu Software Architecture for use in the Wiki
  src/pages/GenericResources/BluArch.png
Labels: GitHub

#144 Db update 09032020
  src/db/Setup/BluTableSetup.sql
  src/db/UploadClass.php
  src/db/uploadPostToDB.php
Labels: Sub-Task

#145 Feature post delay
  src/db/UploadClass.php
  src/db/uploadPostToDB.php
  src/pages/CreatePostPage/createPostPage.php
  src/pages/FunctionBlocks/validUpload.js
Labels: Sub-Task, User Story

#146 Follow button everywhere
  src/db/followToDB.php
  src/db/images/08MDeBCKPAtLhWUc.jpeg
  src/db/images/0nUB5kLSQm9v7hjB.jpeg
  src/db/images/AEEsR2tPWGYtNYc8.jpeg
  src/db/uploadPostToDB.php
  src/pages/FunctionBlocks/followJSFeed.js
  src/pages/HomePage/HomepageBase.php
  src/pages/PopularFeedPage/PopularFeedPage.php
  src/pages/UserPage/UserPage.php
  src/pages/ViewPostPage/viewPost.php
  src/pages/css/FeedStyle.css
  src/pages/css/viewPostStyle.css
  src/tests/CommentToDbTest.php
Labels: Bug

#151 Header rework
  src/pages/Header/Header.html
  src/pages/HomePage/HomepageBase.php
  src/pages/PopularFeedPage/PopularFeedPage.php
  src/pages/UserPage/UserPage.php
  src/pages/css/FeedStyle.css
Labels: Bug, Sub-Task

#153 comments enable on all pages
  src/db/commentToDB.php
  src/db/images/8kn5NbcBxI9rPHeM.jpeg
  src/pages/HomePage/HomepageBase.php
  src/pages/PopularFeedPage/PopularFeedPage.php
  src/pages/UserPage/UserPage.php
  src/pages/css/FeedStyle.css
Labels: Bug

#157 Like/dislike backend
  src/db/commentToDB.php
  src/db/followToDB.php
  src/db/ratingToDB.php
  src/pages/CreatePostPage/createPostPage.php
  src/pages/FunctionBlocks/followJS.js
  src/pages/FunctionBlocks/followJSFeed.js
  src/pages/HomePage/HomepageBase.php
  src/pages/PopularFeedPage/PopularFeedPage.php
  src/pages/UserPage/UserPage.php
  src/pages/ViewPostPage/viewPost.php
  src/pages/ViewPostPage/viewPostClass.php
  src/pages/css/FeedStyle.css
  src/pages/css/viewPostStyle.css
Labels: Sub-Task

#159 Feature/profile pictures
  src/db/DBConfig.php
  src/db/Setup/BluDataSetup.sql
  src/db/Setup/BluTableSetup.sql
  src/db/UploadClass.php
  src/db/uploadPostToDB.php
  src/pages/CreatePostPage/createPostPage.php
  src/pages/CreatePostPage/uploadPostToDB.php
  src/pages/FunctionBlocks/ProfileClass.php
  src/pages/FunctionBlocks/uploadBlock.php
  src/pages/FunctionBlocks/uploadBlockCSSDark.css
  src/pages/FunctionBlocks/validUpload.js
  src/pages/Header/Header.php
  src/pages/HomePage/HomepageBase.php
  src/pages/PopularFeedPage/PopularFeedPage.php
  src/pages/SettingsPage/SettingsPage.php
  src/pages/SettingsPage/SettingsPageStyle.css
  src/pages/SettingsPage/SettingsPageStyleDark.css
  src/pages/SettingsPage/uploadPFP.php
  src/pages/UserPage/UserPage.php
  src/pages/ViewPostPage/viewPost.php
  src/pages/css/FeedStyle.css
  src/pages/css/FeedStyleDark.css
  src/pages/css/viewPostStyle.css
  src/pages/css/viewPostStyleDark.css
  src/tests/UploadPostToDbTest.php
Labels: High-Level, Sub-Task

#163 Profile images fixed, blue link from createPost removed
  src/pages/CreatePostPage/createPostPage.php
  src/pages/Header/Header.php
  src/pages/HomePage/HomepageBase.php
  src/pages/SettingsPage/uploadPFP.php
  src/pages/ViewPostPage/viewPost.php
  src/pages/css/FeedStyle.css
  src/pages/css/FeedStyleDark.css
  src/pages/css/viewPostStyle.css
  src/pages/css/viewPostStyleDark.css
Labels: Bug

#161 Settings page Bug Fixed
  src/pages/CreatePostPage/createPostPage.php
  src/pages/SettingsPage/DeleteAccount.php
  src/pages/SettingsPage/SettingsPage.php
  src/pages/SettingsPage/SettingsPageStyle.css
  src/pages/SettingsPage/SettingsPageStyleDark.css
  src/pages/css/FeedStyleDark.css
Labels: Bug

#164 Notifications if a follower posted in the past 24h
  src/db/notificationsFromDB.php
  src/pages/CreatePostPage/createPostPage.php
  src/pages/Header/Header.php
  src/pages/HomePage/HomepageBase.php
  src/pages/LoginPage/loginPage.php
  src/pages/ViewPostPage/viewPost.php
Labels: Bug

#165 Uploading revised architecture diagram for wiki
  src/pages/GenericResources/BluArchitectureRevised.png
Labels: Doc

#167 Resolving conflict (Architecture Diagram)
  src/pages/GenericResources/BluArchitectureRevised2.png
Labels: Doc
