Repository Aeroponz/SOEN341, pull requests merged in 2020-02, with the labels that each got.

#68 Abstract DB connection method + Image fetch format
  db/BluDBInfo.txt
  db/DBConfig.php
  db/Setup/BluDataSetup.sql
  db/Setup/BluTableSetup.sql
  db/dbPHPexample.php
  db/images/spynapple.gif
Labels: Sub-Task

#74 [Feature] Posting Functionality
  db/Setup/BluTableSetup.sql
  db/dbPHPexample.php
  db/uploadPostToDB.php
  uploadBlock.php
Labels: High-Level

#75 Feature/Continuous_Integration
  .travis.yml
Labels: GitHub, User Story

#79 CI Setup
  .travis.yml
  TestFunction.php
  UnitTest.php
Labels: GitHub, Sub-Task, User Story

#76 Add files and code to follow a user, uses default user numbers
  db/dbPHPexample.php
  db/followToDB.php
  followblock.php
Labels: Sub-Task

#82 Follow and post using real user_id
  Blu/HomepageBase.php
  Blu/followToDB.php
  Blu/loginPage.php
  Blu/uploadPostToDB.php
  db/images/Hwopqj157qjekPpQ.jpeg
Labels: Sub-Task

#108 Alya/reset password page
  src/pages/LoginPage/loginPage.php
  src/pages/ResetPasswordPage/MailTrap/PhpMailer.php
  src/pages/ResetPasswordPage/MailTrap/composer.json
  src/pages/ResetPasswordPage/newPasswordPage.php
  src/pages/ResetPasswordPage/resetPassword.php
  src/pages/ResetPasswordPage/resetPasswordStyle.css
  src/pages/SignUpPage/signUp.php
Labels: High-Level, Sub-Task, User Story

#110 Add new u_id to user_profile table when signing up
  src/pages/SignUpPage/signUp.php
Labels: Bug

#112 Added functions to Login and Sign Up files
  src/pages/FunctionBlocks/checkUsernameAndPassword.php
  src/pages/LoginPage/loginPage.php
  src/pages/SignUpPage/signUp.php
Labels: Bug

#114 Database function refactor + Upload Page CSS
  src/db/DBConfig.php
  src/db/uploadPostToDB.php
  src/pages/CreatePostPage/createPostPage.php
  src/pages/CreatePostPage/createPostPageCSS.css
  src/pages/FunctionBlocks/uploadBlockCSS.css
  src/pages/FunctionBlocks/validUpload.js
Labels: High-Level, Sub-Task

#116 Modal pop up
  SettingUpSMTP
  src/pages/FunctionBlocks/AddEmailToDB.php
  src/pages/LoginPage/followToDB.php
  src/pages/LoginPage/loginFile.txt
  src/pages/LoginPage/loginPage.php
  src/pages/LoginPage/loginPageJS.php
  src/pages/LoginPage/loginPageStyle.css
  src/pages/LoginPage/uploadPostToDB.php
  src/pages/ResetPasswordPage/MailTrap/PhpMailer.php
  src/pages/ResetPasswordPage/newPasswordPage.php
  src/pages/ResetPasswordPage/resetPassword.php
  src/pages/ResetPasswordPage/resetPasswordStyle.css
  src/pages/SignUpPage/ModalPopUp.php
  src/pages/SignUpPage/ModalPopUpStyle.css
  src/pages/SignUpPage/signUp.php
  src/pages/SignUpPage/signUpJS.php
  src/pages/SignUpPage/signUpPageStyle.css
Labels: User Story

#117 Feature/CITestLibrary
  .travis.yml
  src/db/Setup/BluTableSetup.sql
  src/db/followToDB.php
  src/db/uploadPostToDB.php
  src/pages/LoginPage/loginFile.txt
  src/tests/UnitTest.php
Labels: High-Level, User Story

#120 Uploading to DB refactor
  src/db/UploadClass.php
  src/db/uploadPostToDB.php
  src/tests/UnitTest.php
Labels: Bug, Sub-Task
